### PR TITLE
View Source on Github banner

### PR DESCRIPTION
**Pull request by BoldBigflank**
It's easy to go from source to docs, but not the other way around. Until now.

### CODE REVIEW

**Comment by straker** [comment]
I like the idea, but it doesn't quite work. The icon gets in the way of the nav button on mobile and it creates a bar across the heading on desktop. Lastly, the skip navigation icon for some reason gets a `/` appended to the url, so instead of being `href="#main"` and the css applying to that, it gets turned into `href="/#main"` for some reason, so the css fails to find it.

image

image

**Comment by BoldBigflank** [comment]
Ok I'll find some tweaks. I wanted it to be on the page right corner, but didn't want to have to put it in every html file.

**Comment by BoldBigflank** [comment]
Guess just on the index page is better than broken on all pages.

**Comment by straker** [comment]
Thanks!

**Pull request merged**
