### PR TITLE
initPointer works multiple times

### PR DESCRIPTION
**Pull request by BoldBigflank**
Fixes https://github.com/straker/kontra/issues/155

### CODE REVIEW

**Comment by straker** [comment]
Wouldn't it be simpler to have a guard instead of removing and re-adding everything? Something like:

```js
let inited = false;
function initPointer() {
  if (inited) return;

  inited = true;
  // add event listeners
}
```

**Comment by BoldBigflank** [comment]
I don't think that'll work in my case because each time I call `initPointer()` the canvas it's attaching events to is different, so I really intent to do the work again.

**Comment by straker** [comment]
I'm not sure I follow. What you've done is just remove event listeners from one canvas and add them back to the same canvas. I don't see how the canvas is different.

**Comment by BoldBigflank** [comment]
Right, the `removeEventListeners` isn't for my case, specifically. But it makes it possible to call `initPointer()` multiple times without doubling up on events. I still need the `addEventListener`s to do their thing on the new canvas.
I also saw that every time I went to a new game, the `tick` function was being called more times each tick. Adding the `off` before it stopped that.

**Comment by straker** [comment]
This should be fixed via #169

**Pull request closed without merging**
