### PR TITLE
Make tileEngine.renderLayer re-render when dirty

### LINKED ISSUE #116: TileEngine.renderLayer() does not rerender canvas after dirty
If you update the tileEngine layer data and then call `tileEngine.setLayer()`, the changes will not be applied as the function does not call `prerender()` if the tileEngine is dirty.

Essentially we just need to update [`tileEngine.renderLayer`](https://github.com/straker/kontra/blob/master/src/tileEngine.js#L186-L202) to call `prerender()` (`this._p()`) like [we did in the `render` function](https://github.com/straker/kontra/blob/master/src/tileEngine.js#L171-L173).

We should also [add a test to check that it calls `prerender` when dirty](https://github.com/straker/kontra/blob/master/test/unit/tileEngine.spec.js#L82-L106).

### PR DESCRIPTION
**Pull request by reece-bennett**
Fixes #116

@straker Am I right in committing all the generated files (e.g. `kontra.js`)?

### CODE REVIEW

**Comment by straker** [comment]
Yep. You're right to commit the generated files. Thanks for taking this on! I'll take a look at it later today.

**Comment by straker** [comment]
I see what you were saying about needing to call `layerCanvases[name] = undefined`. It seems I was mistaken and we should just need to call `tileEngine._r(layer, canvas.getContext('2d'));` when dirty. That way we don't recreate a canvas every time the map is dirty.

Does doing the following code instead still update the canvas?

```js
if (this._d) {
  this._d = false;
  tileEngine._r(layer, canvas.getContext('2d'));
}
```

**Comment by reece-bennett** [comment]
It does work... kinda. The tiles are updated, but if they have transparency you can still see the previous tile under the new one.

Previous code: https://gfycat.com/coordinatedfavorableherring
Proposed change: https://gfycat.com/blackremotebaboon

**Comment by straker** [comment]
I was afraid of that. Ya, we should clear the canvas before rendering it. Go ahead and update the code with the new changes and test that `tileEngine._r` is called (instead of `tileEngine._p`) and we should be good to go.

Thanks again for taking this on!

**Comment by straker** [comment]
Will make a release later today. Thanks again and great work.

**Pull request merged**
