### PR TITLE
Multi-Touch Support

### LINKED ISSUE #104: Multitouch support
Kontra doesn't support multitouch input. I am not talking about gestures. Is this out of scope or a valid feature request?

**Use Case**

- Scenario: Jump and run game

- Two sprites represent the "move left" and "move right" buttons

- Another sprite represents the "jump" button

- It is required that the combination ("move left" and "jump") or ("move right" and "jump") is detectable in one frame

### PR DESCRIPTION
**Pull request by crhallberg**
Resolves #104.

- Allow passing of a pointer to `getCurrentObject` and `circleRectCollision` to that we can serve the touches beyond the first. 
- Change code to explicitly use `evt.touches` (all active touches) for `onDown` and `onMove` and `evt.changedTouches` (touches being lifted for `touchend`) for `onUp`.
- Add example to prove and debug it! Hosted [here](https://crhallberg.com/beta/kontra/examples/pointer/touches.html) for easy access.

-----

- [x] How do we pass touch data to the user? `pointer.touches`?
- [x] Do we want to handle gestures? `pinchIn`, `pinchOut`, etc.

### CODE REVIEW

**Comment by crhallberg** [comment]
Working on passing the tests.

**Comment by Rayne** [comment]
Nice. :+1:

One minor complaint: The example is flashing all active (touched) tiles when detecting a new touch/finger. I would have expected that only new touches would be highlighted. I think that it could be useful to also display the touch ID. This makes it clear that multi-touch movements can be tracked.

**Comment by crhallberg** [comment]
Adding IDs to the demo is a good idea. This also brings up the point that we need to figure out is if and how we pass all of the touch data to the user.

As far as the flashing goes, I'm not sure if I'm understanding. Green flashes are onOver events. If you take those out, you'll be able to see onDown (blue) and onUp (red) events more easily. I could also be misunderstanding.

**Comment by straker** [comment]
Awesome! I think he means if you are currently touching a square, and then touch another square with another finger, the first square also lights up, so both touches are being activated.

**Comment by Rayne** [comment]
@straker interpreted me right.

Regarding the question whether gestures should be supported: According to the article [Pinch zoom gestures on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures) detecting pinch gestures is quite simple, but requires more than a handful of bytes.

- Would it be possible to implement gestures as optional plugin?

- Which gestures would be relevant?

  - Pinching two fingers: `pinchIn`, `pinchOut` (with direction vector?)

  - Rotating two fingers (counter) clock-wise

  - Scrolling two fingers (in X-, Y- or both directions)

  - Scrolling three fingers (in X-, Y- or both directions)

  - …

**Comment by straker** [comment]
I think gestures as an optional piece of code is a good idea. Current the plugin code is larger than gesture support, so I'm not sure that would work well to save bytes. We may not be able to support optional gestures as the code is now, but I can look into implementing it for v7 hopefully using a similar idea to #125 (being able to compose additional gestures into pointer events).

**Comment by crhallberg** [comment]
The flashing makes sense now. I can fix it and it should make the code smaller too! I'll work on it and maybe a second example to show finger tracking.

**Comment by crhallberg** [comment]
I have made the changes that I expected to stop the event flickering.

I'm seeing a weird effect where a touch help still on my screen moves depending where the other touch is. Something about the electronics on my iPhone SE? I've updated the [hosted example](https://crhallberg.com/beta/kontra/examples/pointer/touches.html) if you want to take a look.

**Comment by Rayne** [comment]
> I'm seeing a weird effect where a touch held still on my screen moves depending on where the other touch is. Some kind of capacitive interference? iPhone SE, btw. I've updated the hosted example if you want to take a look.

I was able to reproduce the problem with a Xiaomi Redmi 3 Pro smartphone. My touch implementation ([Source](https://github.com/Rayne/js13k-lost-robot/blob/d8c60c346cabe2ca5238874cf5394bb42c608dde/public/src/Input/MultiTouchInput.js)) ([Playable here for now](http://pub.datenschuppen.de/js13k/2019/dbe-0003/public/)) has the same the problem.

input-jitter

The circles are added by the video recording app. The squares show the touch positions that are used when calling `update()`. I tried to not move my finger on the right side. I get the same results with your posted example.

**Comment by Rayne** [comment]
The implementation is missing the `touchcancel` event. OS gestures can trigger `touchcancel` events, e.g. when tapping with three fingers "at once" to create a screenshot.

**Comment by crhallberg** [comment]
Alright, I'm now passing the current touch data forwards as `pointer.touches`. It's simplified to `x`, `y`, and `id`. I've added a [second example](https://crhallberg.com/beta/kontra/examples/pointer/tracking.html) that uses this data and shows off how the IDs can be used for tracking. I think you can see the touchcancel if you drag off the canvas before releasing.

One thing that may be useful is instead of passing the touches as `[ { id, x, y} ]` we could pass it as a map like `{ id: { id, x, y } }`. In most browsers, the ID is a unique, incrementing ID. In some browsers though it's just the index, meaning 0 will be repeated over and over. We could combat this with our own ID incrementer but bytes.

**Comment by Rayne** [comment]
The second example does not work on my Xiaomi Redmi 3 Pro (MIUI 9.6.1.0, Android 5.1.1) with the following browsers:

- Chrome
- Firefox
- MIUI Browser

All show a black viewport. The viewport in Firefox spans only the half width of the screen.

**Comment by crhallberg** [comment]
The canvas is intentionally a square to expose the code below. I turned on debug. If you get an error like `undefined is not an object (pointer.touches.length)` you need to clear your cache of the old version of kontra.js.

**Comment by Rayne** [comment]
Great demo. :+1: Got it to run in Firefox and Chrome. I had to reset Chrome but it is now working.

**Comment by straker** [comment]
In Firefox + Mac, I get `evt.changedTouches` is undefined

**Comment by crhallberg** [comment]
I updated the [tracking example](https://crhallberg.com/beta/kontra/examples/pointer/tracking.html) to work with the core Pointer API if no touches are detected (like on a desktop). Does that help your issue?

**Comment by straker** [comment]
Yep, that fixed it for me. Thanks!

**Comment by crhallberg** [comment]
I'd like to find a better way to pass the touch data forward. If [you look at how](https://github.com/straker/kontra/pull/126/files#diff-471aa4eba67c9f546df01ee291c4f581R77) I had to match the event data to the touch data, it's more complex than necessary.

1. A map as discussed above could help with the matching.
2. Setting `pointer.touches = []` instead of undefined will simplify the checks a little.
3. We could pass forward a `changedTouches` of atleast just IDs.

Also, this only the case for the callback events. Sprites using `onUp`, etc., will receive just the relevant touch or pointer.

**Comment by straker** [comment]
What if we change the `pointer.touches` to an object and add each id as the key (`pointer.touches[id] = {}`). Then you can use a for in loop to loop over them?

**Comment by crhallberg** [comment]
I made it so and added a `changed` key to make it dead simple to know which to update in more generic events or cases. [Example updated to match](https://crhallberg.com/beta/kontra/examples/pointer/tracking.html).

**Comment by straker** [comment]
@crhallberg Everything's looking good, are you ready to have this merged?

**Comment by crhallberg** [comment]
Just cleaned up a few things about the examples. Ready to go!

**Pull request merged**
