### PR TITLE
Adds support for flipped sprites

### PR DESCRIPTION
**Pull request by nkholski**
Needed this myself. Merge it if you see it fit.

This add the possibility to render a sprite flipped horizontally or vertically (or both) by specifying flipX and/or flipY in SpriteSheet() argument properties.

### CODE REVIEW

**Comment by wini3d** [comment]
very essential and common feature nowadays if you have sprites that looks exactly the same when flipped, no need for loading another set of images. thanks! :+1:

**Comment by straker** [comment]
Were you able to test flipping the Sprite rather than the animation? If not, i have [a working branch](https://github.com/straker/kontra/blob/flipSprite/src/sprite.js) with a solution that flips the sprite and supports flipping it based on [negative width/height](https://github.com/straker/kontra/blob/flipSprite/src/sprite.js#L368-L375). If you'd like to update this pr with similar changes and add [the tests](https://github.com/straker/kontra/blob/flipSprite/test/unit/sprite.spec.js#L763-L820), I'd love for you to get the credit for it. 

If not, I can merge my branch and close this pr.

**Comment by nkholski** [comment]
I think you can close this and merge your branch. You're right that it belongs to the sprite and not the animation but I'm currently too busy with my js13k contribution :-). Using negative width/height might cause some problems for people using those properties for collisions detection though. I would separate body size and rendered size somehow. (Even if you could add your own bodyWidth/ bodyHeight properties)

**Comment by andre-lima** [comment]
For the animations, i'd suggest we have something like this:
```
    right: {
      frames: '2..6',
      frameRate: 20
    },
    left: {
      frames: '2..6',
      frameRate: 20,
      flipX: true
    },
```
I think it will decouple well the character controller and the animation module in the game code.

**Pull request closed without merging**
