### PR TITLE
fix(pointer): account for camera

### LINKED ISSUE #138: Pointer collision detection
Works incorrectly since checks object.x/y that are actual position on whole map with pointer.x/y that are relative to canvas size.

### PR DESCRIPTION
**Pull request by straker**
Closes #138

### CODE REVIEW

**Comment by blakeearth** [comment]
Hi Steven. Do I need to set the sx and sy for each object? If so, how? They do not seem to be updated when I use `lookAt`.

**Comment by blakeearth** [comment]
Okay, manually setting `sx` and `sy` based on the camera changes has worked for me. My issue was that pointer collisions were not being detected properly after using `lookAt`.

**Comment by straker** [comment]
Could I ask what your setup looked like? Curious if I overlooked something.

**Comment by blakeearth** [comment]
Thanks for replying! Yes. The general setup looks like this:

1. Create an empty scene.
2. Load objects (called "object" in the snippet below) based on JSON from the server and add them to the scene using `Scene.add`. When I load the player object, start the game loop (simplified below): (the camera follows the player object)

`
this.me = object;
this.target = {x: object.x, y: object.y};
//this.cameraOrigin = this.target;
let scene: Scene = this.objects.get("scene");

this.loop = GameLoop({
  update: function() {
    scene.update();
  },
  render: function() {
    this.target = {
      x: lerp(this.target.x, object.x + object.width / 2, 0.1),
      y: lerp(this.target.y, object.y + object.height / 2, 0.1)
    };
    scene.lookAt(this.target);
    scene.render();

    /*for (let persistObject of this.objects.values()) {
      if (persistObject != this.objects.get("scene")) {
        let t = {
          x: this.target.x - this.cameraOrigin.x - persistObject.width / 2,
          y: this.target.y - this.cameraOrigin.y
        };
        persistObject.sx = t.x;
        persistObject.sy = t.y;
      }
    }*/
  }.bind(this)
});

// start the loop
this.loop.start();`

The commented lines are my "fixes" for the unexpected behavior. While the objects rendered in the right spots, their pointer events started to get "off" after moving the camera using `lookAt`.

It all feels a little bit hacky to me, so I would not be surprised to hear that there's a neater way to do this. Thanks for taking a look!

**Comment by straker** [comment]
I see. Ya, I think I completely overlooked pointer events and scene `lookAt`. I'll have to look more closely at that. Thanks for letting me know. I created https://github.com/straker/kontra/issues/294 to keep track of the issue.

**Comment by blakeearth** [comment]
Okay. Thanks for your help!

**Pull request merged**
