### PR TITLE
Fix typo in documentation of `Button`

### PR DESCRIPTION
**Pull request by Rayne**
NB: The build process added parentheses to the generated files.

### CODE REVIEW

**Comment by Rayne** [comment]
I played around with the `Button` implementation and was quite happy with the results at first glance. On the second glance, I was missing the option to add margins to the button. What is the strategy to decorate buttons? I'm totally fine with manually rendering the background of the button but how do you inform the button about the clickable margins?

**Comment by straker** [comment]
Ya I'm still trying to figure out how to do buttons (margins, padding, etc.). Buttons as a sprite image would be easiest for width/height calculations, but I'm not sure that's how everyone does buttons normally (I would assume so). Margins typically aren't clickable, but something like padding would be (giving the image more space around it to click).

**Comment by Rayne** [comment]
You are of course right. I switched margin with padding. I think that it's difficult to decide which features should be supported. The background could also be created based on 9patch images. The question is where to draw the line between required features and feature creep.

**Comment by straker** [comment]
I'm slowly working on the UI Manager code which would need to take into account any padding / margin to correctly calculate position, so it's probably closer to needed rather than creep. Once I get it working all the way I can come back to reevaluate things.

**Pull request merged**
