### PR TITLE
Pointer and Keys init on event

### PR DESCRIPTION
**Pull request by BoldBigflank**

### CODE REVIEW

**Comment by straker** [comment]
The problem I found is using any imported function in the main scope causes a side effect and prevents tree shaking. Using rollup v1.6.0, this is the result of the rollup on the test.js file:

```js
// test.js
import { on } from '../src/kontra.js'

on('foo', () => {})
```

```
// out.js
(function () {
  'use strict';

  let callbacks = {};

  /**
   * Register a callback for an event.
   *
   * @param {string} event - Name of the event
   * @param {function} callback - Function callback
   */
  function on(event, callback) {
    callbacks[event] = callbacks[event] || [];
    callbacks[event].push(callback);
  }

  let canvasEl;

  /**
   * Return the canvas object.
   *
   * @returns {HTMLCanvasElement}
   */
  function getCanvas() {
    return canvasEl;
  }

  /**
   * Noop function
   */

  let callbacks$1 = {};
  let pressedKeys = {};
  let initialized = false;

  /**
   * Execute a function that corresponds to a keyboard key.
   *
   * @param {KeyboardEvent} evt
   */
  function keydownEventHandler(evt) {
    pressedKeys[evt.key] = true;

    if (callbacks$1[evt.key]) {
      callbacks$1[evt.key](evt);
    }
  }

  /**
   * Set the released key to not being pressed.
   *
   * @param {KeyboardEvent} evt
   */
  function keyupEventHandler(evt) {
    pressedKeys[evt.key] = false;
  }

  /**
   * Reset pressed keys.
   */
  function blurEventHandler() {
    pressedKeys = {};
  }

  /**
   * Add keyboard event listeners.
   */
  function initKeys() {
    if (initialized) return;
    addEventListener('keydown', keydownEventHandler);
    addEventListener('keyup', keyupEventHandler);
    addEventListener('blur', blurEventHandler);
    initialized = true;
  }

  on('init', initKeys);

  // save each object as they are rendered to determine which object
  // is on top when multiple objects are the target of an event.
  // we'll always use the last frame's object order so we know
  // the finalized order of all objects, otherwise an object could ask
  // if it's being hovered when it's rendered first even if other objects
  // would block it later in the render order
  let thisFrameRenderOrder = [];
  let lastFrameRenderOrder = [];

  let initialized$1 = false;
  let callbacks$2 = {};
  let pressedButtons = {};

  let buttonMap = {
    0: 'left',
    1: 'middle',
    2: 'right'
  };

  let pointer = {
    x: 0,
    y: 0,
    radius: 5  // arbitrary size
  };

  /**
   * Detection collision between a rectangle and a circlevt.
   * @see https://yal.cc/rectangle-circle-intersection-test/
   *
   * @param {object} object - Object to check collision against.
   */
  function circleRectCollision(object) {
    let x = object.x;
    let y = object.y;
    if (object.anchor) {
      x -= object.width * object.anchor.x;
      y -= object.height * object.anchor.y;
    }

    let dx = pointer.x - Math.max(x, Math.min(pointer.x, x + object.width));
    let dy = pointer.y - Math.max(y, Math.min(pointer.y, y + object.height));
    return (dx * dx + dy * dy) < (pointer.radius * pointer.radius);
  }

  /**
   * Get the first on top object that the pointer collides with.
   *
   * @returns {object} First object to collide with the pointer.
   */
  function getCurrentObject() {

    // if pointer events are required on the very first frame or without a game
    // loop, use the current frame order array
    let frameOrder = (lastFrameRenderOrder.length ? lastFrameRenderOrder : thisFrameRenderOrder);
    let length = frameOrder.length - 1;
    let object, collides;

    for (let i = length; i >= 0; i--) {
      object = frameOrder[i];

      if (object.collidesWithPointer) {
        collides = object.collidesWithPointer(pointer);
      }
      else {
        collides = circleRectCollision(object);
      }

      if (collides) {
        return object;
      }
    }
  }

  /**
   * Execute the onDown callback for an object.
   *
   * @param {MouseEvent|TouchEvent} evt
   */
  function pointerDownHandler(evt) {

    // touchstart should be treated like a left mouse button
    let button = evt.button !== undefined ? buttonMap[evt.button] : 'left';
    pressedButtons[button] = true;
    pointerHandler(evt, 'onDown');
  }

  /**
   * Execute the onUp callback for an object.
   *
   * @param {MouseEvent|TouchEvent} evt
   */
  function pointerUpHandler(evt) {
    let button = evt.button !== undefined ? buttonMap[evt.button] : 'left';
    pressedButtons[button] = false;
    pointerHandler(evt, 'onUp');
  }

  /**
   * Track the position of the mousevt.
   *
   * @param {MouseEvent|TouchEvent} evt
   */
  function mouseMoveHandler(evt) {
    pointerHandler(evt, 'onOver');
  }

  /**
   * Reset pressed buttons.
   */
  function blurEventHandler$1() {
    pressedButtons = {};
  }

  /**
   * Find the first object for the event and execute it's callback function
   *
   * @param {MouseEvent|TouchEvent} evt
   * @param {string} eventName - Which event was called.
   */
  function pointerHandler(evt, eventName) {
    let canvas = getCanvas();

    if (!canvas) return;

    let clientX, clientY;

    if (['touchstart', 'touchmove', 'touchend'].indexOf(evt.type) !== -1) {
      clientX = (evt.touches[0] || evt.changedTouches[0]).clientX;
      clientY = (evt.touches[0] || evt.changedTouches[0]).clientY;
    } else {
      clientX = evt.clientX;
      clientY = evt.clientY;
    }

    let ratio = canvas.height / canvas.offsetHeight;
    let rect = canvas.getBoundingClientRect();
    let x = (clientX - rect.left) * ratio;
    let y = (clientY - rect.top) * ratio;

    pointer.x = x;
    pointer.y = y;

    let object;
    if (evt.target === canvas) {
      evt.preventDefault();
      object = getCurrentObject();
      if (object && object[eventName]) {
        object[eventName](evt);
      }
    }

    if (callbacks$2[eventName]) {
      callbacks$2[eventName](evt, object);
    }
  }

  /**
   * Add pointer event listeners.
   */
  function initPointer() {
    if (initialized$1) return
    let canvas = getCanvas();

    canvas.addEventListener('mousedown', pointerDownHandler);
    canvas.addEventListener('touchstart', pointerDownHandler);
    canvas.addEventListener('mouseup', pointerUpHandler);
    canvas.addEventListener('touchend', pointerUpHandler);
    canvas.addEventListener('blur', blurEventHandler$1);
    canvas.addEventListener('mousemove', mouseMoveHandler);
    canvas.addEventListener('touchmove', mouseMoveHandler);

    // reset object render order on every new frame
    on('tick', () => {
      lastFrameRenderOrder.length = 0;

      thisFrameRenderOrder.map(object => {
        lastFrameRenderOrder.push(object);
      });

      thisFrameRenderOrder.length = 0;
    });
    initialized$1 = true;
  }

  on('init', initPointer);

  /**
   * Save an item to localStorage.
   *
   * @param {string} key - Name to store the item as.
   * @param {*} value - Item to store.
   */

  // let canvas = document.createElement('canvas');
  // document.body.appendChild(canvas);
  // init(canvas);

  on('foo', () => {});

}());
```

**Comment by BoldBigflank** [comment]
I'm getting `on` from `events.js` though, not the main.

**Comment by BoldBigflank** [comment]
Oh I see you used my code to get out.js

**Comment by straker** [comment]
Ya, when I guess I mean the top level scope of the file/module. Main scope was a poor choice of words.

**Comment by BoldBigflank** [comment]
Then I guess Pointer and Keys should be their own classes with a constructor that has the on init event.

**Comment by BoldBigflank** [comment]
Hmm, I just tried the same thing you did and got this:
```javascript
(function () {
  'use strict';

  let callbacks = {};

  /**
   * Register a callback for an event.
   *
   * @param {string} event - Name of the event
   * @param {function} callback - Function callback
   */
  function on(event, callback) {
    callbacks[event] = callbacks[event] || [];
    callbacks[event].push(callback);
  }

  on('foo', () => {});

}());
```

rollup v1.6.0

**Comment by BoldBigflank** [comment]
```javascript
// test.js
import { on } from './src/events.js'

on('foo', () => {})
```
this test does not have that unfurling problem

**Comment by BoldBigflank** [comment]
What's also fun is commenting out the event listener, like this
```javascript
// on('init', initPointer)
```
in pointer.js will still bring that line in on rollup out.js

**Comment by straker** [comment]
I've seem to have this problem. Someone [says rollup removes code when written a certain way], I try it and it doesn't. I'm not sure why my computer results in different results.

**Comment by straker** [comment]
So I tried the changes on a different machine and a clean install, and running rollup on `test.js` file that just contains `import { on } from '../src/kontra.js'` results in all the keyboard and pointer handlers being added to `out.js`. 

I think at this point I'd rather ensure that the result only has what you need rather than getting automatic event handling added. The api will be a bit clunkier, but the built size will be guaranteed smaller.

**Pull request closed without merging**
