### PR TITLE
* expose keymap

### PR DESCRIPTION
**Pull request by Quentie**
* (only possible via preprocessor, so not increasing the default size of lib)

### CODE REVIEW

**Comment by straker** [comment]
This is a great idea. If you're not opposed to it, it's probably something that could always be exposed so it can be extended when needed. It shouldn't increase the size of the lib since it's already part of the keyboard code and is just being added to the `kontra.keys` object.

**Comment by Quentie** [comment]
Exposing it costs a few characters right? Just included the preprocessor so that in case you care for these extra characters ;) Should I simply remove preprocessor statement from pull request or do you want different property name and some jsdocds?

**Comment by straker** [comment]
Ya if you want to remove the preprocess so it's always available, that'd be great. The name is fine, and if you want to add docs that'd be great, otherwise I can add them as I merge it.

**Comment by Quentie** [comment]
ok updated + squashed the pull request. Although not  much changes here now ;) Have a nice evening

**Comment by straker** [comment]
Awesome. I'll get this merged later today. If you wouldn't mind, could you remove the `_` from the variable as it's no longer private? Otherwise I can take care of it during the merge.

Thanks again for the pr.

**Pull request merged**
