### PR TITLE
feat(gamepad): pass buttonName as extra param to gamepad callback

### PR DESCRIPTION
**Pull request by johnedvard**
I have a scenario where I want to register the same listener for several gamepad buttons. I also want to know which button was pressed, which makes it easier to register 1 event listener, and remove 1 event listener (instead of creating multiple listeners)

AS-IS

It's difficult to make a decision to know which button was pressed inside the callback in `onGamepad`

We have to write code like this, but it only works for one key, not an array of keys

```js

onGamepad('south', onPlayerInput.bind({buttonName:'south'})); // not so pretty, and can be difficult to use correctly.

function onPlayerInput(...args){
  console.log('buttonName', this.buttonName});
}

// alternatively
onGamepad('south', (...args) => onPlayerInput(...args,{buttonName:'south'}));


```

TO-BE

Receive the `buttonName` as the third parameter (inside an object for extra flexibility if we want to add more params in the future,) making it easier to know which button initiated the callback.

```js

const onPlayerInput = (gamepad, button, buttonName) => {
  console.log('buttonName', buttonName);
  if(buttonName === 'south') {
    // do something special
  }
}

initControls() {
  onGamepad(['south, north'], onPlayerInput);
}

```

## TODO

- [x] Add additional typings to kontra.d.ts?
    - I don't know if kontra.d.ts is autogenerated or not

### CODE REVIEW

**Comment by straker** [comment]
Nice. I hadn't realized that the GameButton didn't have a property to know which button it was (unlike Keyboard Events). The `kontra.d.ts` file is automatically generated from the JSDoc comments. So you'll need to update the JSDoc comment for `onGamepad` to update the `callback` parameter to include the new return parameter of the function.

**Comment by johnedvard** [comment]
Thanks for the advice on what to change to update `kontra.d.ts`.
Now, I wonder if it's better to do one of the following:

1. Add `buttonName` as an extra attribute to the existing `GamepadButton` interface? (Maybe it will be confusing since we are expanding the default [GamepadButton interface by the browser](https://developer.mozilla.org/en-US/docs/Web/API/GamepadButton)?)
2. Create a new interface for the third argument. Maybe we can call it `GamepadExtras`? This option will cleanup the code a little compared to what I have done so far.

Or maybe you prefer another option?

Also, is it worth creating an extra test for this new feature in `gamepad.spec.js`?

Looking forward to hear what you think.

**Comment by straker** [comment]
I think for now we can pass the `buttonName` as the 3rd parameter itself (not inside another object). Looking at the `updateGamepad` function, I can't see anything else that should be passed to the callback, so just passing the name should be fine.

For the tests, you shouldn't need to add any new ones, but there are a few [that test that the `callback`](https://github.com/straker/kontra/blob/main/test/unit/gamepad.spec.js#L97-L100) was called with certain parameters. We'll want those all updated to include the new `buttonName` parameter.

**Comment by straker** [comment]
Awesome! Nice work, and thanks for the pr.

**Pull request merged**
